name: Run Tests

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Cache pip dependencies to speed up the workflow
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Create a virtual environment and install dependencies
      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt

      # Run the tests
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/
